# Generated by Django 5.0 on 2023-12-23 04:29

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_categoria', models.TextField()),
                ('imagen_categoria', models.ImageField(default='', upload_to='imagenes/')),
                ('activa', models.BooleanField()),
                ('inserted_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'pr_categoria',
            },
        ),
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campania', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('descripcion_campania', models.TextField(blank=True)),
                ('imagen_campania', models.ImageField(default='', upload_to='imagenes/')),
                ('video_campania', models.FileField(blank=True, upload_to='videos_campania/')),
                ('monto_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField(default=datetime.date(2023, 12, 22))),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField()),
                ('inserted_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ManyToManyField(related_name='campanias', to='crownfundingweb.categoria')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'pr_campania',
            },
        ),
        migrations.CreateModel(
            name='Contribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_contribuido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_contribucion', models.DateField()),
                ('comentario_contribucion', models.TextField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('campania_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crownfundingweb.campania')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
